name: Lean
subname: set_sa_layer1
decoder:
  num_lbrd: 2 # Default: 2
  hidden_dim: 512 # Default: 512, used when num_lbrd is >=1
  hidden_dim2: 256 # Default: 256, used when num_lbrd is >=2
lbr_channels: 1024 # Default: 1024
sa:
  channels: 256 # Default: 256
  num_conv_layers: 1  # Default: 2
  num_stacks: 4 # Default: 4
