name: Lean
subname: minimal
decoder:
  num_lbrd: 1 # Default: 2
  hidden_dim: 256 # Default: 512, used when num_lbrd is >=1
  hidden_dim2: 256 # Default: 256, used when num_lbrd is >=2
lbr_channels: 512 # Default: 1024
sa:
  channels: 128 # Default: 256
  num_conv_layers: 1  # Default: 2
  num_stacks: 1 # Default: 4
