batch_size: 16
epoch: 200
learning_rate: 1e-3
gpu: 0
num_point: 1024
optimizer: Adam
weight_decay: 1e-4
normal: True
use_papnet_loader: False
workers: 2
step_size: 50
data_path: '../../datasets/modelnet40_normal_resampled/'
checkpoint_path: 'best_model.pth'

defaults:
  - model: Menghao
  - _self_

hydra:
  run:
    dir: log/cls/${model.name}

  sweep:
    dir: log/cls
    subdir: ${model.name}
